ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "cargo test",
    "cargo clippy",
    "cargo fmt --all",
    "cargo set-version {{version}}",
    "cargo build --release",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "todo-or-boom"
owner = "oknozor"